name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    env:
      CI: true
      NEXTAUTH_URL: "http://localhost:3000"
      NEXTAUTH_SECRET: "testsecret123"
      GOOGLE_CLIENT_ID: "test"
      GOOGLE_CLIENT_SECRET: "test"
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install
      
      - name: Build the project
        run: yarn build

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run tests
        run: npx playwright test
